### ISSUE TITLE
Acquisition du matériel mécanique bras

### ISSUE THREAD

**Issue by JuThe72** [MicahElie/Sym-Bot#10]

**Comment by Chromlox** [comment]
Liste du matériel restant:
- Inserts (en commande)
- 6 vis pour les coupleurs de moteurs
- Petit shaft
- Deux coupleurs

**Comment by Chromlox** [comment]
Matériel ajouté:
- fil groove plus court

**Comment by Chromlox** [comment]
- shaft 26 mm pour la rotation du robot
